# Generated by Django 5.2 on 2025-06-09 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_evento_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='image',
        ),
    ]
