# Generated by Django 5.2 on 2025-06-10 16:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_evento_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo', models.IntegerField(choices=[(1, 'No puedo asignarme al Evento'), (2, 'Problemas de conexión'), (3, 'No recibí el enlace'), (4, 'Otro')])),
                ('mensaje', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
